import type { Metadata } from "next";
import "./globals.css";
import 'leaflet/dist/leaflet.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet.markercluster/dist/MarkerCluster.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet.markercluster/dist/MarkerCluster.Default.css"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
