export type House = {
  id: number;
  title: string;
  lat: number;
  lng: number;
  description: string;
  image: string;
  price?: number;
  city: string;
};

export const houses: House[] = [
  {
    id: 1,
    title: "آپارتمان در تهران‌پارس",
    lat: 35.735,
    lng: 51.55,
    description: "یک واحد آپارتمان شیک در بهترین نقطه تهران‌پارس.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 2,
    title: "خانه ویلایی در تجریش",
    lat: 35.82,
    lng: 51.42,
    description: "خانه ویلایی با حیاط بزرگ و دسترسی عالی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 59,
    title: "خانه ویلایی در تجریش",
    lat: 39.82,
    lng: 60.42,
    description: "خانه ویلایی با حیاط بزرگ و دسترسی عالی.",
    image: "/home.webp",
    city: "الف",
  },
  {
    id: 3,
    title: "پنت‌هاوس در زعفرانیه",
    lat: 35.8,
    lng: 51.4,
    description: "پنت‌هاوس لوکس با ویوی ابدی شهر.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 4,
    title: "واحد اداری در سعادت‌آباد",
    lat: 35.77,
    lng: 51.37,
    description: "واحد اداری مناسب برای شرکت‌های کوچک.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 5,
    title: "آپارتمان نقلی در پونک",
    lat: 35.76,
    lng: 51.33,
    description: "آپارتمان کوچک و دنج برای زوج‌های جوان.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 6,
    title: "خانه کلنگی در شوش",
    lat: 35.65,
    lng: 51.42,
    description: "خانه قدیمی مناسب برای ساخت و ساز.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 7,
    title: "آپارتمان در شهرک غرب",
    lat: 35.76,
    lng: 51.38,
    description: "آپارتمان مدرن در یکی از بهترین برج‌های شهرک غرب.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 8,
    title: "خانه در نارمک",
    lat: 35.72,
    lng: 51.5,
    description: "خانه دلباز با نورگیر عالی در محله‌ای آرام.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 9,
    title: "واحد تجاری در جمهوری",
    lat: 35.69,
    lng: 51.4,
    description: "مغازه تجاری در خیابان پرتردد جمهوری.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 10,
    title: "ویلای شمال تهران",
    lat: 35.85,
    lng: 51.43,
    description: "ویلای دوبلکس با استخر و امکانات کامل.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 11,
    title: "خانه در بازار تهران",
    lat: 35.67,
    lng: 51.4,
    description: "خانه سنتی در قلب بازار تهران.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 12,
    title: "آپارتمان در نیاوران",
    lat: 35.8,
    lng: 51.45,
    description: "آپارتمان بزرگ و خانوادگی در نیاوران.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 13,
    title: "خانه ویلایی در یافت‌آباد",
    lat: 35.63,
    lng: 51.4,
    description: "خانه ویلایی مناسب برای خانواده‌های پرجمعیت.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 14,
    title: "آپارتمان در دولت",
    lat: 35.74,
    lng: 51.44,
    description: "آپارتمان خوش‌ساخت در خیابان دولت.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 15,
    title: "خانه در افسریه",
    lat: 35.65,
    lng: 51.47,
    description: "خانه حیاط‌دار در محله‌ای دنج.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 16,
    title: "آپارتمان در فرمانیه",
    lat: 35.79,
    lng: 51.44,
    description: "آپارتمان لوکس با امکانات هتلینگ.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 17,
    title: "خانه ویلایی در طرشت",
    lat: 35.73,
    lng: 51.33,
    description: "خانه ویلایی با دسترسی به مترو.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 18,
    title: "واحد نقلی در میدان ولیعصر",
    lat: 35.72,
    lng: 51.41,
    description: "سوئیت مبله در مرکز شهر.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 19,
    title: "ویلای دریاچه چیتگر",
    lat: 35.7,
    lng: 51.29,
    description: "ویلای مدرن با ویوی دریاچه چیتگر.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 20,
    title: "خانه در جنت‌آباد",
    lat: 35.74,
    lng: 51.33,
    description: "خانه بازسازی شده در جنت‌آباد شمالی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 21,
    title: "آپارتمان در شهر ری",
    lat: 35.58,
    lng: 51.42,
    description: "آپارتمان ارزان و مناسب در شهر ری.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 22,
    title: "خانه باغ در فرمانیه",
    lat: 35.81,
    lng: 51.42,
    description: "خانه باغ با فضای سبز بسیار زیاد.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 23,
    title: "واحد اداری در ملاصدرا",
    lat: 35.74,
    lng: 51.38,
    description: "دفتر کار مدرن با امکانات کامل.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 24,
    title: "آپارتمان نوساز در امیرآباد",
    lat: 35.7,
    lng: 51.39,
    description: "آپارتمان نوساز با طراحی مدرن و زیبا.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 25,
    title: "خانه ویلایی در حکیمیه",
    lat: 35.75,
    lng: 51.53,
    description: "خانه ویلایی با حیاط بزرگ و امکانات کامل.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 26,
    title: "سوئیت مبله در تهران‌نو",
    lat: 35.72,
    lng: 51.57,
    description: "سوئیت شیک و مبله نزدیک به مراکز خرید.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 27,
    title: "آپارتمان در دروس",
    lat: 35.74,
    lng: 51.43,
    description: "آپارتمان مناسب دانشجویان و زوج‌های جوان.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 28,
    title: "خانه ویلایی در محله وزرا",
    lat: 35.73,
    lng: 51.4,
    description: "خانه ویلایی با دسترسی آسان به خیابان‌های اصلی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 29,
    title: "واحد تجاری در خیابان ولیعصر",
    lat: 35.7,
    lng: 51.4,
    description: "مغازه تجاری مناسب برای کسب و کارهای کوچک.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 30,
    title: "ویلای دوبلکس در لشگرآباد",
    lat: 35.69,
    lng: 51.36,
    description: "ویلای دوبلکس با امکانات کامل رفاهی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 31,
    title: "آپارتمان در شهرک اکباتان",
    lat: 35.72,
    lng: 51.31,
    description: "آپارتمان مدرن و نوساز با امکانات ورزشی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 32,
    title: "خانه باغ در لویزان",
    lat: 35.75,
    lng: 51.6,
    description: "خانه باغ بزرگ با فضای سبز دلنشین.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 33,
    title: "واحد اداری در مرکز شهر",
    lat: 35.68,
    lng: 51.42,
    description: "دفتر اداری در مرکز شهر با دسترسی عالی.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 34,
    title: "آپارتمان در شهرک گلستان",
    lat: 35.71,
    lng: 51.35,
    description: "آپارتمان نقلی با قیمت مناسب.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 35,
    title: "خانه ویلایی در نارمک",
    lat: 35.72,
    lng: 51.52,
    description: "خانه ویلایی با حیاط بزرگ و دسترسی به مدرسه.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 36,
    title: "سوئیت مبله در خیابان انقلاب",
    lat: 35.69,
    lng: 51.41,
    description: "سوئیت مبله نزدیک دانشگاه تهران.",
    image: "/home.webp",
    city: "تهران",
  },
  {
    id: 37,
    title: "آپارتمان لوکس در زعفرانیه",
    lat: 35.79,
    lng: 51.39,
    description: "آپارتمان لوکس با امکانات هتلینگ.",
    image: "/home.webp",
    city: "تهران",
  },
];
